import { useEffect } from 'react'
import { usePreferences } from './preferencesContext'

const englishPairs: Array<[string, string]> = [
  ['Tus ideas merecen llegar a producción.', 'Your ideas deserve to reach production.'],
  ['Tus ideas merecen', 'Your ideas deserve'],
  ['llegar a producción.', 'to reach production.'],
  ['Organiza tus proyectos, mantén el foco y convierte tu próximo side project en algo real.', 'Organize your projects, stay focused, and turn your next side project into something real.'],
  ['La herramienta que necesitaba para dejar de abandonar proyectos a mitad de camino.', 'The tool I needed to stop abandoning projects halfway through.'],
  ['Un developer con demasiadas ideas', 'A developer with too many ideas'],
  ['vos@email.com', 'you@example.com'],
  ['CONSTRUYE CON INTENCIÓN', 'BUILD WITH INTENTION'],
  ['Bienvenido de nuevo', 'Welcome back'],
  ['Continúa construyendo donde lo dejaste.', 'Keep building where you left off.'],
  ['¿No tienes cuenta?', "Don't have an account?"],
  ['¿Ya tienes cuenta?', 'Already have an account?'],
  ['Crea una gratis', 'Create one for free'],
  ['Inicia sesión', 'Sign in'],
  ['Iniciar sesión', 'Sign in'],
  ['Creá tu cuenta', 'Create your account'],
  ['Crear cuenta', 'Create account'],
  ['Tu próximo proyecto empieza acá.', 'Your next project starts here.'],
  ['¿Olvidaste tu contraseña?', 'Forgot your password?'],
  ['Recuperar contraseña', 'Reset password'],
  ['Te enviaremos un enlace seguro para elegir una contraseña nueva.', 'We will send you a secure link to choose a new password.'],
  ['Revisá tu bandeja de entrada y también la carpeta de spam.', 'Check your inbox and your spam folder.'],
  ['Enviar enlace', 'Send link'],
  ['Enviando...', 'Sending...'],
  ['Volver al inicio de sesión', 'Back to sign in'],
  ['Nueva contraseña', 'New password'],
  ['Elegí una contraseña segura que no hayas usado anteriormente.', 'Choose a secure password you have not used before.'],
  ['Confirmar contraseña', 'Confirm password'],
  ['Tu contraseña', 'Your password'],
  ['Creá una contraseña segura', 'Create a secure password'],
  ['Volvé a escribirla', 'Type it again'],
  ['¿Cómo te llamamos?', 'What should we call you?'],
  ['Mostrar contraseña', 'Show password'],
  ['Ocultar contraseña', 'Hide password'],
  ['Mostrar confirmación', 'Show confirmation'],
  ['Ocultar confirmación', 'Hide confirmation'],
  ['Bloq Mayús está activado', 'Caps Lock is on'],
  ['Seguridad', 'Strength'],
  ['Sin contraseña', 'No password'],
  ['Muy débil', 'Very weak'],
  ['Débil', 'Weak'],
  ['Buena', 'Good'],
  ['Fuerte', 'Strong'],
  ['8 caracteres', '8 characters'],
  ['Una mayúscula', 'One uppercase letter'],
  ['Una minúscula', 'One lowercase letter'],
  ['Un número', 'One number'],
  ['Un símbolo', 'One symbol'],
  ['recomendado', 'recommended'],
  ['Guardar contraseña', 'Save password'],
  ['Ingresá un email válido.', 'Enter a valid email.'],
  ['Ingresá al menos 6 caracteres.', 'Enter at least 6 characters.'],
  ['Ingresá al menos 2 caracteres.', 'Enter at least 2 characters.'],
  ['Usá al menos 8 caracteres.', 'Use at least 8 characters.'],
  ['Las contraseñas no coinciden.', 'Passwords do not match.'],
  ['El email o la contraseña no son correctos.', 'The email or password is incorrect.'],
  ['Confirmá tu email antes de iniciar sesión.', 'Confirm your email before signing in.'],
  ['No pudimos completar la operación. Intentá nuevamente.', 'We could not complete the operation. Please try again.'],
  ['Procesando...', 'Processing...'],
  ['Preparando tu espacio...', 'Preparing your workspace...'],
  ['Cerrar barra lateral', 'Collapse sidebar'],
  ['Abrir barra lateral', 'Expand sidebar'],
  ['Mis tareas', 'My tasks'],
  ['Proyectos', 'Projects'],
  ['Tareas', 'Tasks'],
  ['Ideas', 'Ideas'],
  ['Inicio', 'Home'],
  ['Ajustes', 'Settings'],
  ['Configuración', 'Settings'],
  ['Cerrar sesión', 'Sign out'],
  ['Modo claro', 'Light mode'],
  ['Modo oscuro', 'Dark mode'],
  ['TU ESPACIO DE TRABAJO', 'YOUR WORKSPACE'],
  ['Este es el pulso general de todo lo que estás construyendo.', 'This is the big picture of everything you are building.'],
  ['Ver proyectos', 'View projects'],
  ['TU PRÓXIMO PASO', 'YOUR NEXT STEP'],
  ['La prioridad más conveniente para continuar ahora está en', 'The best priority to continue with now is in'],
  ['Todo al día', 'All caught up'],
  ['No tenés tareas pendientes. Podés capturar una idea o preparar el siguiente proyecto.', 'You have no pending tasks. Capture an idea or prepare your next project.'],
  ['Abrir ideas', 'Open ideas'],
  ['Todavía no guardaste sesiones. Tu historial empezará con el próximo Focus.', 'You have not saved any sessions yet. Your history will begin with your next Focus session.'],
  ['Ver último avance', 'View latest progress'],
  ['Es el proyecto que más atención necesita en este momento.', 'This project needs the most attention right now.'],
  ['Revisar proyecto', 'Review project'],
  ['Espacio nuevo', 'New workspace'],
  ['Creá tu primer proyecto para empezar a medir su progreso.', 'Create your first project to start tracking its progress.'],
  ['Proyectos activos', 'Active projects'],
  ['Tareas pendientes', 'Pending tasks'],
  ['Ideas por evaluar', 'Ideas to review'],
  ['Minutos Focus hoy', 'Focus minutes today'],
  ['Objetivo Focus cumplido', 'Focus goal completed'],
  ['Objetivo Focus de hoy', "Today's Focus goal"],
  ['Resumen rápido', 'Quick overview'],
  ['Deslizá para ver más', 'Swipe to see more'],
  ['Creá, buscá y administrá todo lo que estás construyendo.', 'Create, find, and manage everything you are building.'],
  ['Nuevo proyecto', 'New project'],
  ['Proyectos totales', 'Total projects'],
  ['En progreso', 'In progress'],
  ['Pausados', 'Paused'],
  ['Tareas completadas', 'Completed tasks'],
  ['Todos tus proyectos', 'All your projects'],
  ['Buscar proyecto...', 'Search projects...'],
  ['Sin descripción todavía.', 'No description yet.'],
  ['Stack por definir', 'Stack to be defined'],
  ['Progreso', 'Progress'],
  ['Actualizado', 'Updated'],
  ['Crear nuevo proyecto', 'Create new project'],
  ['Convertí esa idea en algo real.', 'Turn that idea into something real.'],
  ['Cargando proyectos...', 'Loading projects...'],
  ['No pudimos cargar tus proyectos.', 'We could not load your projects.'],
  ['Volver a proyectos', 'Back to projects'],
  ['Editar proyecto', 'Edit project'],
  ['Eliminar proyecto', 'Delete project'],
  ['Resumen', 'Overview'],
  ['Detalles', 'Details'],
  ['Nueva tarea', 'New task'],
  ['Crear primera tarea', 'Create first task'],
  ['Todavía no hay tareas en este proyecto.', 'There are no tasks in this project yet.'],
  ['Nombre del proyecto', 'Project name'],
  ['Descripción', 'Description'],
  ['Tecnologías', 'Technologies'],
  ['Repositorio', 'Repository'],
  ['URL pública', 'Public URL'],
  ['Estado', 'Status'],
  ['Idea', 'Idea'],
  ['Pausado', 'Paused'],
  ['Terminado', 'Completed'],
  ['Crear proyecto', 'Create project'],
  ['Guardar cambios', 'Save changes'],
  ['Guardar tarea', 'Save task'],
  ['Editar tarea', 'Edit task'],
  ['Crear tarea', 'Create task'],
  ['Título', 'Title'],
  ['Fecha límite', 'Due date'],
  ['Prioridad', 'Priority'],
  ['Pendiente', 'To do'],
  ['Completada', 'Completed'],
  ['Alta prioridad', 'High priority'],
  ['Prioridad media', 'Medium priority'],
  ['Prioridad baja', 'Low priority'],
  ['Alta', 'High'],
  ['Media', 'Medium'],
  ['Baja', 'Low'],
  ['Cancelar', 'Cancel'],
  ['Guardando...', 'Saving...'],
  ['Cargando tareas...', 'Loading tasks...'],
  ['No pudimos cargar tus tareas.', 'We could not load your tasks.'],
  ['No hay tareas que coincidan con los filtros.', 'No tasks match the filters.'],
  ['Crear una desde un proyecto', 'Create one from a project'],
  ['Soltá una tarea acá', 'Drop a task here'],
  ['Ver proyecto', 'View project'],
  ['BANDEJA DE IDEAS', 'IDEA INBOX'],
  ['Ideas para después', 'Ideas for later'],
  ['Guardá lo que se te ocurre antes de que se pierda.', 'Save what comes to mind before it gets lost.'],
  ['Nueva idea', 'New idea'],
  ['Nuevas', 'New'],
  ['Para evaluar', 'To review'],
  ['Archivadas', 'Archived'],
  ['IDEA RECOMENDADA', 'RECOMMENDED IDEA'],
  ['Revisar evaluación', 'Review score'],
  ['Buscar por título, detalle o tecnología...', 'Search by title, details, or technology...'],
  ['Todos los estados', 'All statuses'],
  ['Cargando ideas...', 'Loading ideas...'],
  ['No pudimos cargar tus ideas.', 'We could not load your ideas.'],
  ['Convertir en proyecto', 'Convert to project'],
  ['Creando proyecto...', 'Creating project...'],
  ['Tu próxima gran idea empieza acá', 'Your next great idea starts here'],
  ['Anotá cualquier concepto, aunque todavía no esté definido.', 'Write down any concept, even if it is not fully defined yet.'],
  ['Anotar primera idea', 'Add first idea'],
  ['Evaluación rápida', 'Quick score'],
  ['Ayuda a decidir qué idea merece avanzar.', 'Helps decide which idea deserves to move forward.'],
  ['Entusiasmo', 'Excitement'],
  ['Utilidad', 'Usefulness'],
  ['Dificultad', 'Difficulty'],
  ['Tiempo estimado', 'Estimated time'],
  ['horas', 'hours'],
  ['Guardar idea', 'Save idea'],
  ['MODO FOCUS', 'FOCUS MODE'],
  ['Prepará tu sesión', 'Prepare your session'],
  ['Configuración de la próxima sesión', 'Next session setup'],
  ['Sesión en curso', 'Session in progress'],
  ['Expandir modo Focus', 'Expand Focus mode'],
  ['Minimizar modo Focus', 'Minimize Focus mode'],
  ['Expandir', 'Expand'],
  ['Minimizar', 'Minimize'],
  ['Proyecto', 'Project'],
  ['Duración', 'Duration'],
  ['Personalizada', 'Custom'],
  ['Minutos', 'Minutes'],
  ['Elegí el objetivo', 'Choose your objective'],
  ['PRIORIDAD ALTA', 'HIGH PRIORITY'],
  ['PRIORIDAD MEDIA', 'MEDIUM PRIORITY'],
  ['PRIORIDAD BAJA', 'LOW PRIORITY'],
  ['Abrir proyecto', 'Open project'],
  ['Ya hay una sesión activa', 'A session is already active'],
  ['Proyectos que necesitan una decisión', 'Projects that need a decision'],
  ['días sin actividad', 'days without activity'],
  ['Reactivar', 'Reactivate'],
  ['Pausar conscientemente', 'Pause intentionally'],
  ['Revisar alcance', 'Review scope'],
  ['¡Sesión completada!', 'Session completed!'],
  ['No guardar', "Don't save"],
  ['Guardar sesión', 'Save session'],
  ['Sesión libre', 'Free session'],
  ['Ver proyecto', 'View project'],
  ['Pausar', 'Pause'],
  ['Continuar', 'Continue'],
  ['Finalizar', 'Finish'],
  ['¿Qué resolviste?', 'What did you accomplish?'],
  ['¿Qué quedó pendiente?', 'What is still pending?'],
  ['Mensaje para tu próxima sesión', 'Message for your next session'],
  ['¿Cómo rindió la sesión?', 'How productive was the session?'],
  ['Historial Focus', 'Focus history'],
  ['Tiempo invertido y resultados concretos de cada sesión.', 'Time invested and concrete results from each session.'],
  ['Tiempo enfocado', 'Focused time'],
  ['Sesiones guardadas', 'Saved sessions'],
  ['Promedio por sesión', 'Average per session'],
  ['Tiempo cumplido', 'Time completed'],
  ['Finalizada manualmente', 'Finished manually'],
  ['Resuelto', 'Completed'],
  ['Próximo paso', 'Next step'],
  ['Sesión registrada', 'Session recorded'],
  ['Sin notas de cierre.', 'No closing notes.'],
  ['Todavía no hay sesiones guardadas', 'No saved sessions yet'],
  ['Cuando completes un Focus y elijas guardarlo, aparecerá acá.', 'When you complete and save a Focus session, it will appear here.'],
  ['EDITAR SESIÓN FOCUS', 'EDIT FOCUS SESSION'],
  ['Actualizar el registro', 'Update record'],
  ['Objetivos de la sesión', 'Session objectives'],
  ['Valoración', 'Rating'],
  ['TU ESPACIO', 'YOUR WORKSPACE'],
  ['Personalizá la experiencia, tu cuenta y la privacidad de tus datos.', 'Customize your experience, account, and data privacy.'],
  ['EXPERIENCIA', 'EXPERIENCE'],
  ['Cómo funciona tu espacio', 'How your workspace works'],
  ['Apariencia, navegación, Focus y asistencia.', 'Appearance, navigation, Focus, and assistance.'],
  ['Idioma', 'Language'],
  ['Elegí el idioma de toda la interfaz.', 'Choose the language for the entire interface.'],
  ['Idioma de la aplicación', 'Application language'],
  ['Español', 'Spanish'],
  ['Preferencias Focus', 'Focus preferences'],
  ['Personalizá cómo empiezan, terminan y se muestran tus sesiones.', 'Customize how your sessions start, end, and appear.'],
  ['Duración predeterminada', 'Default duration'],
  ['Posición del temporizador', 'Timer position'],
  ['Objetivo diario', 'Daily goal'],
  ['Iniciar minimizado', 'Start minimized'],
  ['Sonido al finalizar', 'Completion sound'],
  ['Confirmar antes de descartar', 'Confirm before discarding'],
  ['Usar historial en el asistente', 'Use history in the assistant'],
  ['Apariencia', 'Appearance'],
  ['Elegí el tema o seguí automáticamente la configuración del dispositivo.', 'Choose a theme or automatically follow your device settings.'],
  ['Claro', 'Light'],
  ['Oscuro', 'Dark'],
  ['Sistema', 'System'],
  ['Preferencias del espacio', 'Workspace preferences'],
  ['Definí dónde empezar y cómo organizar tu trabajo.', 'Choose where to start and how to organize your work.'],
  ['Página de inicio', 'Start page'],
  ['Inicio y resumen', 'Home and overview'],
  ['Vista predeterminada de tareas', 'Default task view'],
  ['Lista', 'List'],
  ['Asistente DevHub', 'DevHub Assistant'],
  ['Controlá su presencia y el tipo de ayuda que querés recibir.', 'Control its presence and the kind of help you want.'],
  ['Mostrar asistente', 'Show assistant'],
  ['Sugerencias rápidas', 'Quick suggestions'],
  ['Recomendación al abrir', 'Recommendation on open'],
  ['Ayuda y recorrido', 'Help and tour'],
  ['Repetir tutorial', 'Replay tutorial'],
  ['CUENTA Y SEGURIDAD', 'ACCOUNT AND SECURITY'],
  ['Tu identidad y acceso', 'Your identity and access'],
  ['Datos personales, contraseña y sesiones abiertas.', 'Personal data, password, and active sessions.'],
  ['Perfil', 'Profile'],
  ['Nombre', 'Name'],
  ['Email', 'Email'],
  ['Contraseña', 'Password'],
  ['Actualizar contraseña', 'Update password'],
  ['Sesiones', 'Sessions'],
  ['Cerrar esta sesión', 'Sign out this session'],
  ['Cerrar todas', 'Sign out everywhere'],
  ['DATOS Y PRIVACIDAD', 'DATA AND PRIVACY'],
  ['Datos y privacidad', 'Data and privacy'],
  ['Exportar mis datos', 'Export my data'],
  ['Eliminar cuenta', 'Delete account'],
  ['Eliminar mi cuenta', 'Delete my account'],
  ['Diario de desarrollo', 'Development journal'],
  ['Una memoria automática de cada avance.', 'An automatic log of every step forward.'],
  ['Decisiones técnicas', 'Technical decisions'],
  ['Nueva', 'New'],
  ['Automático', 'Automatic'],
  ['Todo lo necesario para publicar con confianza.', 'Everything you need to ship with confidence.'],
  ['PORTFOLIO AUTOMÁTICO', 'AUTOMATIC PORTFOLIO'],
  ['Convertí el proceso en una historia', 'Turn the process into a story'],
  ['Generar texto', 'Generate text'],
  ['NUEVA DECISIÓN', 'NEW DECISION'],
  ['Documentar una elección', 'Document a choice'],
  ['Contexto', 'Context'],
  ['Decisión', 'Decision'],
  ['Guardar decisión', 'Save decision'],
  ['TEXTO PARA PORTFOLIO', 'PORTFOLIO COPY'],
  ['Copiar texto', 'Copy text'],
  ['Copiado', 'Copied'],
  ['Cerrar', 'Close'],
  ['Atrás', 'Back'],
  ['Siguiente', 'Next'],
  ['Empezar a construir', 'Start building'],
  ['Construí con intención', 'Build with intention'],
  ['Todo tu trabajo, con una dirección clara', 'All your work, moving in a clear direction'],
  ['DevHub reúne proyectos, tareas, ideas y sesiones de foco para ayudarte a decidir qué continuar y terminar lo que empezaste.', 'DevHub brings projects, tasks, ideas, and Focus sessions together so you can decide what to continue and finish what you started.'],
  ['Un resumen para saber qué hacer hoy', 'An overview to know what to do today'],
  ['Cada proyecto con tareas y progreso', 'Every project with tasks and progress'],
  ['Historial real de tu tiempo enfocado', 'A real history of your focused time'],
  ['Empezá por el pulso general', 'Start with the big picture'],
  ['Inicio te muestra la próxima tarea recomendada, tus minutos Focus, ideas pendientes y el proyecto que necesita atención.', 'Home shows your next recommended task, Focus minutes, pending ideas, and the project that needs attention.'],
  ['Revisá tu próximo paso', 'Review your next step'],
  ['Detectá proyectos frenados', 'Spot stalled projects'],
  ['Consultá tu objetivo Focus diario', 'Check your daily Focus goal'],
  ['Retomá sin reconstruir todo en tu cabeza', 'Pick up without rebuilding everything in your head'],
  ['DevHub recuerda tu último resultado, lo que quedó pendiente y el próximo paso. El radar detecta proyectos que están perdiendo impulso.', 'DevHub remembers your latest result, what remains pending, and the next step. The radar detects projects that are losing momentum.'],
  ['Iniciá una sesión de rescate corta', 'Start a short rescue session'],
  ['Dejá un mensaje para tu próxima sesión', 'Leave a message for your next session'],
  ['Descubrí tu Project DNA con el uso', 'Discover your Project DNA as you use DevHub'],
  ['Dale un hogar a cada proyecto', 'Give every project a home'],
  ['Creá un proyecto, definí su estado y stack, y mantené sus tareas, enlaces y avances en un solo lugar.', 'Create a project, define its status and stack, and keep its tasks, links, and progress in one place.'],
  ['Usá estados para reflejar su momento', 'Use statuses to reflect its current stage'],
  ['Mirá el progreso y Project Pulse', 'Review progress and Project Pulse'],
  ['Entrá al proyecto para trabajar en detalle', 'Open the project to work in detail'],
  ['Separá lo accionable de lo posible', 'Separate what is actionable from what is possible'],
  ['Mis tareas reúne el trabajo de todos los proyectos. Ideas es tu bandeja para guardar oportunidades sin convertirlas en compromisos todavía.', 'My tasks brings work from every project together. Ideas is your inbox for opportunities that are not commitments yet.'],
  ['Filtrá tareas por proyecto y prioridad', 'Filter tasks by project and priority'],
  ['Usá lista o Kanban', 'Use list or Kanban view'],
  ['Convertí una buena idea en proyecto cuando esté lista', 'Turn a good idea into a project when it is ready'],
  ['Trabajá con un objetivo concreto', 'Work toward a concrete objective'],
  ['Elegí un proyecto, una duración y las tareas de la sesión. Al terminar, guardá qué resolviste, qué quedó pendiente y cuál es el próximo paso.', 'Choose a project, duration, and session tasks. When you finish, save what you accomplished, what remains pending, and the next step.'],
  ['El temporizador sigue activo mientras navegás', 'The timer stays active while you navigate'],
  ['Podés minimizarlo para que no moleste', 'You can minimize it so it stays out of the way'],
  ['El historial construye una memoria real del proyecto', 'History builds a real memory of the project'],
  ['Personalizá DevHub a tu manera', 'Customize DevHub your way'],
  ['El asistente usa tus datos para ayudarte a decidir. Desde Ajustes podés controlar su comportamiento, el tema, Focus, tu cuenta y este tutorial.', 'The assistant uses your data to help you decide. From Settings you can control its behavior, theme, Focus, your account, and this tour.'],
  ['Preguntá qué proyecto continuar', 'Ask which project to continue'],
  ['Configurá metas y duración de Focus', 'Configure Focus goals and duration'],
  ['Volvé a abrir este recorrido cuando quieras', 'Open this tour again whenever you want'],
  ['¡Hola! Soy el asistente de DevHub. Puedo ayudarte a decidir qué continuar y revisar tus proyectos, tareas, ideas y sesiones Focus.', 'Hi! I am the DevHub assistant. I can help you decide what to continue and review your projects, tasks, ideas, and Focus sessions.'],
  ['Puedo recomendarte un proyecto, buscar tareas vencidas, revisar ideas y resumir tus sesiones Focus, incluyendo tiempo trabajado, resultados y próximos pasos.', 'I can recommend a project, find overdue tasks, review ideas, and summarize your Focus sessions, including time worked, results, and next steps.'],
  ['Preguntá sobre tu trabajo...', 'Ask about your work...'],
  ['Abrir asistente', 'Open assistant'],
  ['Cerrar asistente', 'Close assistant'],
  ['Limpiar conversación', 'Clear conversation'],
  ['Mensaje para el asistente', 'Message for the assistant'],
  ['Ver más sugerencias', 'View more suggestions'],
  ['¿Qué proyecto debería continuar?', 'Which project should I continue?'],
  ['¿Tengo tareas vencidas?', 'Do I have overdue tasks?'],
  ['¿Cuántas tareas tengo pendientes?', 'How many pending tasks do I have?'],
  ['¿Qué ideas tengo pendientes?', 'Which ideas do I have pending?'],
  ['¿Cómo vienen mis sesiones Focus?', 'How are my Focus sessions going?'],
  ['¿Qué proyecto necesita rescate?', 'Which project needs rescuing?'],
  ['¿Tengo proyectos pausados?', 'Do I have paused projects?'],
  ['¿Cómo está el pulse de mis proyectos?', 'How is my project pulse?'],
  ['Tengo 30 minutos, ¿qué hago?', 'I have 30 minutes, what should I do?'],
  ['Todavía estoy cargando tu información. Probá nuevamente en un momento.', 'I am still loading your information. Try again in a moment.'],
  ['No encontré proyectos activos para recomendarte. Podés crear uno desde una idea.', 'I could not find active projects to recommend. You can create one from an idea.'],
  ['No encontré proyectos activos para reactivar. Podés convertir una idea en proyecto.', 'I could not find active projects to reactivate. You can turn an idea into a project.'],
  ['No encontré un proyecto activo para preparar una sesión.', 'I could not find an active project for a session.'],
  ['No tenés tareas pendientes. ¡Excelente trabajo!', 'You have no pending tasks. Great work!'],
  ['No tenés ideas pendientes. Podés anotar una nueva cuando aparezca.', 'You have no pending ideas. Add one when it comes up.'],
  ['No tenés proyectos pausados.', 'You have no paused projects.'],
  ['¡Vas al día! No tenés tareas vencidas.', 'You are all caught up! You have no overdue tasks.'],
  ['No hay tareas pendientes con prioridad alta.', 'There are no high-priority pending tasks.'],
  ['Ninguna tiene prioridad alta.', 'None are high priority.'],
  ['Todavía no entendí esa consulta. Probá preguntándome qué proyecto continuar, si tenés tareas vencidas, cuáles son prioritarias o qué ideas están pendientes.', 'I did not understand that question yet. Ask which project to continue, whether you have overdue tasks, which are high priority, or which ideas are pending.'],
  ['Dale un hogar a tu próxima gran idea.', 'Give your next great idea a home.'],
  ['CAPTURAR IDEA', 'CAPTURE IDEA'],
  ['¿Qué querés construir?', 'What do you want to build?'],
  ['Actualizar idea', 'Update idea'],
  ['EDITAR IDEA', 'EDIT IDEA'],
  ['Escribí un título para la idea.', 'Enter a title for the idea.'],
  ['Problema, posibles usuarios, funciones que imaginás...', 'Problem, potential users, features you imagine...'],
  ['Probá cambiando la búsqueda o los filtros.', 'Try changing the search or filters.'],
  ['Buscar ideas', 'Search ideas'],
  ['Filtrar ideas por estado', 'Filter ideas by status'],
  ['Buscar tareas', 'Search tasks'],
  ['Buscar tarea...', 'Search tasks...'],
  ['Filtrar por proyecto', 'Filter by project'],
  ['Filtrar por prioridad', 'Filter by priority'],
  ['Filtrar por estado', 'Filter by status'],
  ['Ej. Diseñar página principal', 'E.g. Design the home page'],
  ['Agregá el contexto necesario...', 'Add the necessary context...'],
  ['¿Qué estás construyendo y por qué?', 'What are you building and why?'],
  ['Ingresá una URL válida.', 'Enter a valid URL.'],
  ['No pudimos guardar el proyecto. Revisá los datos e intentá nuevamente.', 'We could not save the project. Review the information and try again.'],
  ['No pudimos guardar la tarea. Intentá nuevamente.', 'We could not save the task. Try again.'],
  ['No pudimos guardar la idea. Intentá nuevamente.', 'We could not save the idea. Try again.'],
  ['No pudimos guardar los cambios.', 'We could not save the changes.'],
  ['No pudimos convertir la idea en proyecto.', 'We could not convert the idea into a project.'],
  ['No pudimos eliminar el proyecto. Intentá nuevamente.', 'We could not delete the project. Try again.'],
  ['No pudimos eliminar la tarea.', 'We could not delete the task.'],
  ['No pudimos eliminar la idea.', 'We could not delete the idea.'],
  ['No pudimos modificar la sesión.', 'We could not update the session.'],
  ['No pudimos guardar el cierre. Intentá nuevamente.', 'We could not save the session summary. Try again.'],
  ['No pudimos cambiar el estado de la tarea.', 'We could not change the task status.'],
  ['No pudimos cambiar el estado de la idea.', 'We could not change the idea status.'],
  ['No pudimos conectarnos con Supabase. Revisá la configuración del despliegue.', 'We could not connect to Supabase. Review the deployment configuration.'],
  ['La conexión con Supabase no está configurada en este despliegue.', 'The Supabase connection is not configured in this deployment.'],
  ['Ya existe una cuenta con ese email.', 'An account with that email already exists.'],
  ['Repetí la contraseña para confirmarla.', 'Repeat the password to confirm it.'],
  ['Las contraseñas coinciden.', 'Passwords match.'],
  ['La contraseña todavía no cumple todos los requisitos.', 'The password does not meet all requirements yet.'],
  ['Datos guardados. Confirmá el nuevo email desde el mensaje que te enviamos.', 'Changes saved. Confirm the new email from the message we sent you.'],
  ['Tu contraseña se actualizó correctamente.', 'Your password was updated successfully.'],
  ['Abrir memoria del proyecto', 'Open project memory'],
  ['Todavía no hay una memoria de trabajo. Esta sesión puede definir el próximo paso.', 'There is no work memory yet. This session can define the next step.'],
  ['Todavía no registraste qué resolviste.', 'You have not recorded what you accomplished yet.'],
  ['Todavía por descubrir', 'Still to be discovered'],
  ['Tu próxima sesión puede ser la que reactive un proyecto.', 'Your next session could reactivate a project.'],
  ['Definir el próximo avance concreto.', 'Define the next concrete step forward.'],
  ['Definir una tarea pequeña que deje un resultado visible.', 'Define a small task that produces a visible result.'],
  ['Descripción definida', 'Description defined'],
  ['Stack tecnológico definido', 'Technology stack defined'],
  ['Diseño responsive revisado', 'Responsive design reviewed'],
  ['Descripción para portfolio', 'Portfolio description'],
  ['Proyecto publicado', 'Project published'],
  ['Registrar un avance o aprendizaje...', 'Record progress or a lesson learned...'],
  ['Agregar al diario', 'Add to journal'],
  ['Los próximos cambios aparecerán automáticamente acá.', 'Future changes will appear here automatically.'],
  ['Recordá por qué elegiste cada camino.', 'Remember why you chose each path.'],
  ['Documentá elecciones de arquitectura, librerías y alcance.', 'Document architecture, library, and scope choices.'],
  ['¿Qué problema o alternativas existían?', 'What problem or alternatives existed?'],
  ['¿Qué decidiste y por qué?', 'What did you decide and why?'],
  ['Ej. Usar Supabase en lugar de API propia', 'E.g. Use Supabase instead of a custom API'],
  ['Un objetivo por línea', 'One objective per line'],
  ['Ej. Terminé el login y corregí la validación...', 'E.g. Finished the login and fixed validation...'],
  ['Recordame continuar con...', 'Remind me to continue with...'],
  ['Algo por revisar...', 'Something to review...'],
  ['Valoración de la sesión', 'Session rating'],
  ['¿Descartar esta sesión sin guardarla?', 'Discard this session without saving it?'],
  ['¿Eliminar esta sesión Focus del historial? Esta acción no se puede deshacer.', 'Delete this Focus session from history? This action cannot be undone.'],
  ['¿Seguro que querés cerrar sesión?', 'Are you sure you want to sign out?'],
  ['¿Seguro que querés cerrar esta sesión?', 'Are you sure you want to sign out this session?'],
  ['¿Cerrar tu sesión en todos los dispositivos?', 'Sign out on all devices?'],
  ['¿Querés eliminar tu cuenta? Se borrarán todos tus proyectos, tareas, ideas y sesiones Focus.', 'Delete your account? All projects, tasks, ideas, and Focus sessions will be deleted.'],
  ['Esta acción es permanente y no se puede deshacer. ¿Confirmás que querés eliminar todo?', 'This action is permanent and cannot be undone. Are you sure you want to delete everything?'],
  ['Actualizá la información principal.', 'Update the main information.'],
  ['El nombre debe tener al menos 2 caracteres.', 'The name must be at least 2 characters long.'],
  ['Ingresá un nombre de al menos 2 caracteres.', 'Enter a name with at least 2 characters.'],
  ['No pudimos actualizar la contraseña. Solicitá un enlace nuevo.', 'We could not update the password. Request a new link.'],
  ['No pudimos actualizar la contraseña. Volvé a iniciar sesión o usá la recuperación por email.', 'We could not update the password. Sign in again or use email recovery.'],
  ['No pudimos enviar el enlace. Intentá nuevamente.', 'We could not send the link. Try again.'],
  ['No pudimos cerrar la sesión. Intentá nuevamente.', 'We could not sign out. Try again.'],
  ['No pudimos cerrar todas las sesiones.', 'We could not close all sessions.'],
  ['No pudimos eliminar la cuenta. Volvé a iniciar sesión e intentá nuevamente.', 'We could not delete the account. Sign in again and try once more.'],
  ['Revisá tu email para confirmar el acceso. Si ese correo ya tenía una cuenta, iniciá sesión o recuperá la contraseña.', 'Check your email to confirm access. If that email already had an account, sign in or reset your password.'],
  ['Tu cuenta y todos sus datos fueron eliminados correctamente.', 'Your account and all its data were deleted successfully.'],
  ['EDITAR', 'EDIT'],
  ['NUEVA', 'NEW'],
  ['Editar sesión', 'Edit session'],
  ['Eliminar sesión', 'Delete session'],
  ['Eliminar', 'Delete'],
  ['Editar', 'Edit'],
  ['Abrir Mis tareas', 'Open My tasks'],
  ['Revisar tareas', 'Review tasks'],
  ['Revisar ideas', 'Review ideas'],
  ['Explorar ideas', 'Explore ideas'],
  ['Abrir Ideas', 'Open Ideas'],
  ['Abrir Project Pulse', 'Open Project Pulse'],
  ['Ver historial Focus', 'View Focus history'],
  ['Ver Build Receipt', 'View Build Receipt'],
  ['Ver pendientes', 'View pending tasks'],
  ['Ver tareas', 'View tasks'],
  ['Mostrame las tareas prioritarias', 'Show me high-priority tasks'],
  ['Dame un resumen general', 'Give me an overview'],
  ['Mostrame mi semana construyendo', 'Show me my building week'],
  ['Sin servicios de IA externos', 'No external AI services'],
  ['Ver sugerencias anteriores', 'View previous suggestions'],
  ['Enviar', 'Send'],
  ['Estos proyectos necesitan atención:', 'These projects need attention:'],
  ['Estas son tus prioridades altas:', 'These are your high priorities:'],
  ['Proyectos pausados:', 'Paused projects:'],
  ['Recomendación para hoy:', "Today's recommendation:"],
  ['Último resultado:', 'Latest result:'],
  ['Quedó pendiente:', 'Still pending:'],
  ['Siguiente acción:', 'Next action:'],
  ['Pendiente:', 'Pending:'],
  ['Contexto:', 'Context:'],
  ['PASO 1 · INICIO', 'STEP 1 · HOME'],
  ['PASO 6 · ASISTENTE Y AJUSTES', 'STEP 6 · ASSISTANT AND SETTINGS'],
  ['Stack en definición', 'Stack being defined'],
  ['El proyecto está publicado y disponible para probar.', 'The project is published and available to try.'],
  ['El proyecto documenta el proceso, los retos técnicos y los aprendizajes obtenidos.', 'The project documents the process, technical challenges, and lessons learned.'],
  ['Entre las decisiones técnicas principales se encuentran:', 'The main technical decisions include:'],
  ['Retomá', 'Resume'],
  ['Volvé exactamente donde lo dejaste', 'Return exactly where you left off'],
  ['DevHub reconstruye el contexto y reduce el esfuerzo de retomar.', 'DevHub rebuilds context and reduces the effort of getting back to work.'],
  ['Mi semana', 'My week'],
  ['SESIÓN DE RESCATE SUGERIDA', 'SUGGESTED RESCUE SESSION'],
  ['Actividad', 'Activity'],
  ['SIGUIENTE ACCIÓN', 'NEXT ACTION'],
  ['Tu último resultado guardado', 'Your latest saved result'],
  ['Empezar rescate de', 'Start a rescue session of'],
  ['Ver memoria', 'View memory'],
  ['RADAR DE ABANDONO', 'ABANDONMENT RADAR'],
  ['Proyectos que pueden perder impulso', 'Projects that may lose momentum'],
  ['Buen ritmo general', 'Good overall momentum'],
  ['Ningún proyecto muestra señales de abandono.', 'No project shows signs of abandonment.'],
  ['Tu forma real de construir', 'How you actually build'],
  ['Duración ideal', 'Ideal duration'],
  ['Franja más productiva', 'Most productive time'],
  ['Sesiones aprovechadas', 'Productive sessions'],
  ['Días con foco', 'Focused days'],
  ['Tu patrón aparecerá pronto', 'Your pattern will appear soon'],
  ['Completá algunas sesiones Focus para descubrirlo.', 'Complete a few Focus sessions to discover it.'],
  ['Tu semana construyendo', 'Your building week'],
  ['DEVHUB · ÚLTIMOS 7 DÍAS', 'DEVHUB · LAST 7 DAYS'],
  ['minutos enfocado', 'focused minutes'],
  ['tareas completadas', 'completed tasks'],
  ['proyectos activos', 'active projects'],
  ['retomados', 'resumed'],
  ['Seguir construyendo también cuenta.', 'Keeping on building counts too.'],
  ['Copiar resumen', 'Copy summary'],
  ['MEMORIA DEL PROYECTO', 'PROJECT MEMORY'],
  ['Tu contexto para volver', 'Your context for returning'],
  ['Lo importante de la última sesión, preparado para tu yo del futuro.', 'What matters from your latest session, prepared for your future self.'],
  ['Reconstruyendo contexto...', 'Rebuilding context...'],
  ['ÚLTIMO RESULTADO', 'LATEST RESULT'],
  ['QUEDÓ PENDIENTE', 'STILL PENDING'],
  ['No hay pendientes registrados.', 'No pending items recorded.'],
  ['MENSAJE PARA TU PRÓXIMA SESIÓN', 'MESSAGE FOR YOUR NEXT SESSION'],
  ['ACCIÓN MÍNIMA VIABLE', 'MINIMUM VIABLE ACTION'],
  ['minutos para recuperar el impulso sin sobrecargarte.', 'minutes to regain momentum without overloading yourself.'],
  ['Retomar durante', 'Resume for'],
  ['Abajo a la izquierda', 'Bottom left'],
  ['Arriba a la derecha', 'Top right'],
  ['Arriba a la izquierda', 'Top left'],
  ['Activa el botón flotante en toda la aplicación.', 'Enables the floating button throughout the app.'],
  ['Analiza tu trabajo y propone automáticamente un proyecto.', 'Analyzes your work and automatically suggests a project.'],
  ['Borrá permanentemente tu cuenta y todos sus datos.', 'Permanently delete your account and all its data.'],
  ['Buenos días,', 'Good morning,'],
  ['Buscar proyectos', 'Search projects'],
  ['Cargando proyecto...', 'Loading project...'],
  ['Cerrando sesiones...', 'Signing out sessions...'],
  ['Control de tu información', 'Control of your information'],
  ['Descargá una copia de toda tu información.', 'Download a copy of all your information.'],
  ['Descargá una copia o eliminá permanentemente la cuenta.', 'Download a copy or permanently delete the account.'],
  ['El asistente usará esta meta para interpretar tu ritmo diario.', 'The assistant will use this goal to understand your daily pace.'],
  ['El proyecto no existe o no tenés acceso.', 'The project does not exist or you do not have access.'],
  ['El próximo paso siempre visible.', 'Keep the next step always visible.'],
  ['Evita perder accidentalmente una sesión que todavía no guardaste.', 'Prevents accidentally losing a session you have not saved yet.'],
  ['Incluye tu perfil, proyectos, tareas e ideas en un archivo JSON.', 'Includes your profile, projects, tasks, and ideas in a JSON file.'],
  ['La información que identifica tu cuenta.', 'The information that identifies your account.'],
  ['Las nuevas sesiones mostrarán únicamente el tiempo restante.', 'New sessions will only show the remaining time.'],
  ['Muestra preguntas relacionadas debajo de la conversación.', 'Shows related questions below the conversation.'],
  ['No encontramos proyectos con', 'We found no projects matching'],
  ['No pudimos encontrar el proyecto.', 'We could not find the project.'],
  ['No pudimos exportar tus datos.', 'We could not export your data.'],
  ['No vas a poder recuperar proyectos, tareas, ideas, recursos ni sesiones Focus después de eliminarla.', 'You will not be able to recover projects, tasks, ideas, resources, or Focus sessions after deleting it.'],
  ['Podés cerrar solamente este dispositivo o revocar todas las sesiones activas.', 'You can sign out only this device or revoke all active sessions.'],
  ['Podés elegir el lugar que menos interfiera con tu trabajo.', 'Choose the position that interferes least with your work.'],
  ['Protegé la cuenta y controlá dónde está abierta.', 'Protect your account and control where it is signed in.'],
  ['Repasá las funciones principales de DevHub.', 'Review the main DevHub features.'],
  ['Reproduce un aviso breve cuando el contador llega a cero.', 'Plays a short alert when the timer reaches zero.'],
  ['Se abrirá después de iniciar sesión y al tocar el logo.', 'It will open after signing in and when you select the logo.'],
  ['Se seleccionará automáticamente al preparar un nuevo Focus.', 'It will be selected automatically when preparing a new Focus session.'],
  ['TU TRABAJO', 'YOUR WORK'],
  ['Todas las prioridades', 'All priorities'],
  ['Todo lo pendiente, sin importar en qué proyecto esté.', 'Everything pending, regardless of its project.'],
  ['Todos los proyectos', 'All projects'],
  ['Tus datos se guardaron correctamente.', 'Your data was saved successfully.'],
  ['Volvé a ver el tutorial inicial para recordar dónde está cada herramienta.', 'View the initial tour again to remember where each tool is.'],
  ['Última sesión en', 'Latest session in'],
  ['Asistente de DevHub', 'DevHub assistant'],
  ['Definí una tarea pequeña que deje un resultado visible.', 'Define a small task that produces a visible result.'],
  ['está activo y puede ser un buen lugar para definir el próximo paso', 'is active and can be a good place to define the next step'],
  ['Elegí si querés guardar esta sesión. Podés sumar contexto ahora o editarlo después.', 'Choose whether to save this session. You can add context now or edit it later.'],
  ['Este proyecto no tiene tareas pendientes. Podés iniciar una sesión libre para definir el próximo paso.', 'This project has no pending tasks. You can start a free session to define the next step.'],
  ['seleccionadas · podés cambiar la sugerencia', 'selected · you can change the suggestion'],
  ['Generá una presentación usando la descripción, el stack, las tareas y las decisiones del proyecto.', 'Generate a presentation using the project description, stack, tasks, and decisions.'],
  ['Preparando inteligencia del proyecto...', 'Preparing project intelligence...'],
  ['Listo para publicar', 'Ready to ship'],
  ['Cargando sesiones...', 'Loading sessions...'],
  ['PASO 3 · PROYECTOS', 'STEP 3 · PROJECTS'],
  ['PASO 4 · TAREAS E IDEAS', 'STEP 4 · TASKS AND IDEAS'],
  ['Ej. App para organizar recetas', 'E.g. App for organizing recipes'],
  ['% de potencial ·', '% potential ·'],
  ['proyecto visible', 'visible project'],
  ['proyectos visibles', 'visible projects'],
  ['min hoy', 'min today'],
  ['idea pendiente', 'pending idea'],
  ['tarea pendiente', 'pending task'],
  ['tareas pendientes', 'pending tasks'],
  ['tarea vencida', 'overdue task'],
  ['tareas vencidas', 'overdue tasks'],
  ['Volver', 'Back'],
  ['sesiones', 'sessions'],
  ['sesión', 'session'],
  ['proyectos', 'projects'],
  ['proyecto', 'project'],
  ['tareas', 'tasks'],
  ['tarea', 'task'],
  ['hoy', 'today'],
  ['de', 'of'],
  ['Saltar al contenido principal', 'Skip to main content'],
  ['Cerrar notificación', 'Dismiss notification'],
  ['Cargando pantalla...', 'Loading screen...'],
  ['Cargando contenido...', 'Loading content...'],
  ['Tu primer proyecto empieza acá', 'Your first project starts here'],
  ['Creá un espacio para organizar tareas, decisiones y avances.', 'Create a space to organize tasks, decisions, and progress.'],
  ['Definí una acción pequeña y concreta para empezar a avanzar.', 'Define one small, concrete action to start moving forward.'],
  ['Proyecto creado correctamente.', 'Project created successfully.'],
  ['Proyecto actualizado correctamente.', 'Project updated successfully.'],
  ['Proyecto eliminado correctamente.', 'Project deleted successfully.'],
  ['Tarea creada correctamente.', 'Task created successfully.'],
  ['Tarea actualizada correctamente.', 'Task updated successfully.'],
  ['Tarea eliminada correctamente.', 'Task deleted successfully.'],
  ['Estado de la tarea actualizado.', 'Task status updated.'],
  ['Idea creada correctamente.', 'Idea created successfully.'],
  ['Idea actualizada correctamente.', 'Idea updated successfully.'],
  ['Idea eliminada correctamente.', 'Idea deleted successfully.'],
  ['Estado de la idea actualizado.', 'Idea status updated.'],
  ['Idea convertida en proyecto.', 'Idea converted into a project.'],
  ['Preferencias guardadas correctamente.', 'Preferences saved successfully.'],
  ['Contraseña actualizada correctamente.', 'Password updated successfully.'],
  ['Exportación preparada correctamente.', 'Export prepared successfully.'],
  ['Ver demo interactiva', 'View interactive demo'],
  ['DEMO INTERACTIVA', 'INTERACTIVE DEMO'],
  ['INTERACTIVE DEMO', 'INTERACTIVE DEMO'],
  ['DEMO INTERACTIVA · INICIO', 'INTERACTIVE DEMO · HOME'],
  ['DEMO INTERACTIVA · PROYECTOS', 'INTERACTIVE DEMO · PROJECTS'],
  ['DEMO INTERACTIVA · TAREAS', 'INTERACTIVE DEMO · TASKS'],
  ['DEMO INTERACTIVA · IDEAS', 'INTERACTIVE DEMO · IDEAS'],
  ['Ver los 3', 'View all 3'],
  ['Usar modo claro', 'Use light mode'],
  ['Usar modo oscuro', 'Use dark mode'],
  ['MODO DEMO', 'DEMO MODE'],
  ['Datos ficticios · nada se guarda', 'Sample data · nothing is saved'],
  ['Salir de la demo', 'Exit demo'],
  ['Así se siente construir con foco', 'This is what focused building feels like'],
  ['Crear mi espacio', 'Create my workspace'],
  ['Todo tu trabajo, en contexto', 'All your work, in context'],
  ['El inicio reúne prioridades, progreso y el próximo paso.', 'Home brings together priorities, progress, and the next step.'],
  ['Proyectos que cuentan una historia', 'Projects that tell a story'],
  ['Cada proyecto conserva tareas, decisiones, Focus y aprendizajes.', 'Each project keeps tasks, decisions, Focus, and lessons together.'],
  ['Una vista clara de lo pendiente', 'A clear view of what is pending'],
  ['Probá completar una tarea para ver el progreso de la demo.', 'Complete a task to see the demo progress update.'],
  ['Ideas antes de que se pierdan', 'Ideas before they get lost'],
  ['Capturá, evaluá y convertí una idea en proyecto cuando esté lista.', 'Capture, evaluate, and turn an idea into a project when it is ready.'],
  ['Volver al inicio', 'Back to the start'],
  ['Siguiente', 'Next'],
  ['Minutos Focus esta semana', 'Focus minutes this week'],
  ['Una tarea concreta para mantener el impulso en', 'A concrete task to keep momentum in'],
  ['Empezar ahora', 'Start now'],
  ['PULSO GENERAL', 'OVERALL PULSE'],
  ['Completá una tarea de la demo para actualizar este indicador.', 'Complete a demo task to update this indicator.'],
  ['PROYECTOS DESTACADOS', 'FEATURED PROJECTS'],
  ['En qué estás construyendo', 'What you are building'],
  ['Todos los proyectos en un solo lugar', 'All projects in one place'],
  ['TODAS TUS TAREAS', 'ALL YOUR TASKS'],
  ['Un próximo paso para cada proyecto', 'A next step for every project'],
  ['Lo próximo todavía puede cambiar', 'What comes next can still change'],
  ['Demo actualizada. Los cambios no se guardan.', 'Demo updated. Changes are not saved.'],
  ['En una cuenta real podrías guardar una nueva idea acá.', 'In a real account you could save a new idea here.'],
  ['Idea lista para convertirse en proyecto.', 'Idea ready to become a project.'],
  ['¿Listo para probarlo con tus proyectos?', 'Ready to try it with your projects?'],
  ['Creá una cuenta gratis y empezá con tu primera idea.', 'Create a free account and start with your first idea.'],
  ['Ver paso', 'View step'],
  ['PRESENTACIÓN PÚBLICA', 'PUBLIC SHOWCASE'],
  ['Tu proyecto está visible', 'Your project is live'],
  ['Compartí lo que construiste', 'Share what you built'],
  ['PUBLICADO', 'PUBLISHED'],
  ['PRIVADO', 'PRIVATE'],
  ['Generá una página profesional para mostrar el proyecto, su stack y sus avances.', 'Create a professional page to showcase the project, its stack, and its progress.'],
  ['Solo se muestran datos del proyecto y tareas completadas. Tus notas, decisiones y fechas permanecen privadas.', 'Only project details and completed tasks are shown. Your notes, decisions, and dates stay private.'],
  ['Dirección personalizada', 'Custom address'],
  ['Activar página pública', 'Publish project page'],
  ['Guardar enlace', 'Save link'],
  ['Copiar enlace', 'Copy link'],
  ['Ver página', 'View page'],
  ['Despublicar', 'Unpublish'],
  ['Cargando presentación...', 'Loading showcase...'],
  ['ENLACE NO DISPONIBLE', 'LINK UNAVAILABLE'],
  ['Este proyecto no está publicado', 'This project is not published'],
  ['Es posible que el enlace haya cambiado o que su creador lo haya despublicado.', 'The link may have changed or its creator may have unpublished it.'],
  ['Conocer DevHub', 'Discover DevHub'],
  ['PROYECTO DESTACADO · POR', 'FEATURED PROJECT · BY'],
  ['Un proyecto construido con intención, foco y mejora continua.', 'A project built with intention, focus, and continuous improvement.'],
  ['Ver proyecto', 'View project'],
  ['Ver repositorio', 'View repository'],
  ['completado', 'complete'],
  ['El stack detrás del proyecto', 'The stack behind the project'],
  ['Stack todavía no publicado.', 'Stack not published yet.'],
  ['AVANCES', 'PROGRESS'],
  ['Hitos completados', 'Completed milestones'],
  ['Los próximos avances aparecerán acá.', 'Future progress will appear here.'],
  ['CREADO CON DEVHUB', 'BUILT WITH DEVHUB'],
  ['Las buenas ideas merecen llegar a producción.', 'Great ideas deserve to reach production.'],
  ['Organizá tus proyectos, mantené el foco y convertí el proceso en una historia que puedas mostrar.', 'Organize your projects, stay focused, and turn the process into a story you can showcase.'],
]

const sortedPairs = [...englishPairs].sort((a, b) => b[0].length - a[0].length)
const originalText = new WeakMap<Text, string>()
const originalAttributes = new WeakMap<Element, Map<string, string>>()
const translatedAttributes = ['placeholder', 'aria-label', 'title']

function toEnglish(value: string): string {
  if (value.includes('\n')) return value.split('\n').map(toEnglish).join('\n')
  const protectedSegments: string[] = []
  const protect = (segment: string) => {
    protectedSegments.push(segment)
    return `\uE000${protectedSegments.length - 1}\uE001`
  }
  const labelledBullet = value.match(/^(• (?:Último resultado|Pendiente|Próximo paso|Quedó pendiente|Siguiente acción): )(.*)$/)
  if (value.trimStart().startsWith('• ') && !labelledBullet) return value
  let result = value
  if (labelledBullet) result = labelledBullet[1] + protect(labelledBullet[2])
  result = result.replace(/[“”][^“”]*[“”]/g, segment => segment.includes('La herramienta que necesitaba para dejar de abandonar proyectos a mitad de camino.') ? segment : protect(segment))
  for (const [spanish, english] of sortedPairs) {
    const atomicLabel = !spanish.includes(' ') && !/[.!?¿¡]/.test(spanish)
    if (atomicLabel && result.trim() !== spanish) continue
    result = result.split(spanish).join(english)
  }
  result = result
    .replace(/^Editar (.+)$/, 'Edit $1')
    .replace(/^Eliminar (.+)$/, 'Delete $1')
    .replace(/^Completar (.+)$/, 'Complete $1')
    .replace(/^Reabrir (.+)$/, 'Reopen $1')
    .replace(/^Mover (.+)$/, 'Move $1')
    .replace(/^Estado de (.+)$/, 'Status of $1')
    .replace(/^Marcar (.+) como pendiente$/, 'Mark $1 as pending')
    .replace(/^Retomá (.+)$/, 'Resume $1')
    .replace(/hace (\d+) días/g, '$1 days ago')
    .replace(/(\d+) días sin actividad/g, '$1 days without activity')
    .replace(/(\d+) tareas/g, '$1 tasks')
    .replace(/(\d+) tarea\b/g, '$1 task')
    .replace(/(\d+) proyectos/g, '$1 projects')
    .replace(/(\d+) proyecto\b/g, '$1 project')
    .replace(/(\d+) minutos enfocados/g, '$1 focused minutes')
    .replace(/(\d+) min enfocado/g, '$1 focused min')
    .replace(/(\d+) seleccionadas/g, '$1 selected')
    .replace(/\bayer\b/g, 'yesterday')
    .replace(/\bhoy\b/g, 'today')
  return result.replace(/\uE000(\d+)\uE001/g, (_, index: string) => protectedSegments[Number(index)])
}

function translate(value: string, language: 'es' | 'en') {
  return language === 'en' ? toEnglish(value) : value
}

function skipTextNode(node: Text) {
  const parent = node.parentElement
  if (!parent) return true
  if (parent.matches('.focus-history-notes p:not(.empty)') && node.previousSibling instanceof HTMLElement && node.previousSibling.tagName === 'STRONG') return true
  if (parent.matches('.decision-list small') && node !== parent.firstChild) return true
  if (parent.matches('.timeline strong') && parent.closest('article')?.querySelector('i.note')) return true
  return Boolean(parent.closest('script,style,[data-no-translate],.assistant-message.user,.project-card h3,.idea-card h2,.task-content strong,.global-task-main>strong,.kanban-card>strong,.project-title h1,.focus-project h3'))
}

function translateTree(root: Node, language: 'es' | 'en', preserveOriginal = false) {
  const texts: Text[] = []
  if (root.nodeType === Node.TEXT_NODE) texts.push(root as Text)
  else {
    const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT)
    while (walker.nextNode()) texts.push(walker.currentNode as Text)
  }

  for (const node of texts) {
    if (skipTextNode(node) || !node.nodeValue?.trim()) continue
    const previousOriginal = originalText.get(node)
    const expected = previousOriginal ? translate(previousOriginal, language) : undefined
    if (!previousOriginal || (!preserveOriginal && node.nodeValue !== expected)) originalText.set(node, node.nodeValue)
    node.nodeValue = translate(originalText.get(node) ?? node.nodeValue, language)
  }

  const elements = root.nodeType === Node.ELEMENT_NODE
    ? [root as Element, ...(root as Element).querySelectorAll('*')]
    : []
  for (const element of elements) {
    let originals = originalAttributes.get(element)
    if (!originals) {
      originals = new Map()
      originalAttributes.set(element, originals)
    }
    for (const attribute of translatedAttributes) {
      const current = element.getAttribute(attribute)
      if (!current) continue
      const previousOriginal = originals.get(attribute)
      const expected = previousOriginal ? translate(previousOriginal, language) : undefined
      if (!previousOriginal || (!preserveOriginal && current !== expected)) originals.set(attribute, current)
      element.setAttribute(attribute, translate(originals.get(attribute) ?? current, language))
    }
  }
}

export function LanguageRuntime() {
  const { preferences } = usePreferences()
  const language = preferences.language

  useEffect(() => {
    document.documentElement.lang = language
    const observe = () => observer.observe(document.body, { childList: true, subtree: true, characterData: true, attributes: true, attributeFilter: translatedAttributes })
    const apply = (root: Node = document.body) => {
      observer?.disconnect()
      translateTree(root, language, true)
      observe()
    }
    const observer = new MutationObserver(mutations => {
      observer.disconnect()
      for (const mutation of mutations) {
        if (mutation.type === 'characterData') translateTree(mutation.target, language)
        else if (mutation.type === 'attributes') translateTree(mutation.target, language)
        else mutation.addedNodes.forEach(node => translateTree(node, language))
      }
      observe()
    })
    apply()
    return () => observer.disconnect()
  }, [language])

  return null
}
